Backend/.gitignore, Backend/build.gradle, Backend/src/main/java/com/ecobyte/ecocycle/application/auth/AuthService.java, Backend/src/main/java/com/ecobyte/ecocycle/application/auth/JwtTokenProvider.java, Backend/src/main/java/com/ecobyte/ecocycle/config/RestTemplateConfig.java, Backend/src/main/java/com/ecobyte/ecocycle/domain/user/Role.java, Backend/src/main/java/com/ecobyte/ecocycle/domain/user/User.java, Backend/src/main/java/com/ecobyte/ecocycle/domain/user/UserRepository.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/ErrorResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/GoogleProfileResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/GoogleTokenResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/LoginResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/exception/auth/ExpiredTokenException.java, Backend/src/main/java/com/ecobyte/ecocycle/exception/auth/GoogleOAuthFailureException.java, Backend/src/main/java/com/ecobyte/ecocycle/exception/auth/InvalidTokenException.java, Backend/src/main/java/com/ecobyte/ecocycle/exception/auth/TokenException.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/AuthController.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/ControllerAdvice.java, Backend/src/main/java/com/ecobyte/ecocycle/support/GoogleClient.java, Backend/src/main/resources/application-oauth.yml, Backend/src/main/resources/application.yml, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/LoginAcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/application/auth/AuthServiceTest.java
Close #6 
feature/be/login -> main
- 구글 로그인을 구현한다.
- test가 log를 남기지 않고 있다.
=> [BE] Oauth 2.0 로그인 기능 구현

Frontend/login.html, Frontend/style/reset.css, Frontend/style/style.css
Close #
feature/ -> main
- 요구사항
- 변경사항
=> [FE] 로그인 페이지 작성

Backend/src/main/java/com/ecobyte/ecocycle/ApplicationStartupRunner.java, Backend/src/main/java/com/ecobyte/ecocycle/application/auth/AdminAspect.java, Backend/src/main/java/com/ecobyte/ecocycle/application/auth/AdminAuthorization.java, Backend/src/main/java/com/ecobyte/ecocycle/application/auth/AuthService.java, Backend/src/main/java/com/ecobyte/ecocycle/domain/user/User.java, Backend/src/main/java/com/ecobyte/ecocycle/exception/auth/AdminAuthorizationException.java, Backend/src/test/java/com/ecobyte/ecocycle/application/auth/AuthServiceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/domain/user/UserTest.java
Close #25 
feature/be/authorize-admin -> main
- 관리자 권한을 인가할 수 있는 기능을 구현한다.
-  관리자 email을 yml 파일로 이동
- 필요없는 상수 제거
=> [BE] 관리자 인가 기능

Backend/src/main/java/com/ecobyte/ecocycle/config/RestTemplateConfig.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/auth/AuthController.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/LoginAcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/UserAcceptanceTest.java
Close #30 
refactor/be/login -> main
- 바뀐 API에 맞게 POST -> GET으로 변경
=> [BE] 로그인 API 수정

Backend/build.gradle, Backend/src/main/java/com/ecobyte/ecocycle/application/RecyclingProductService.java, Backend/src/main/java/com/ecobyte/ecocycle/domain/product/RecyclingProduct.java, Backend/src/main/java/com/ecobyte/ecocycle/domain/product/RecyclingProductRepository.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/request/RecyclingProductRequest.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/RecyclingProductResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/ControllerAdvice.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/RecyclingProductController.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/AcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/LoginAcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/RecyclingProductAcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/UserAcceptanceTest.java
Close #28 
feature/be/add-admin -> main
- 제품 추가 API 구현
- 현재 관리자 인가 처리가 안돼서 수정 필요.
=> [BE] 제품 추가 기능

Backend/src/main/java/com/ecobyte/ecocycle/application/auth/AdminAspect.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/ControllerAdvice.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/AcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/RecyclingProductAcceptanceTest.java
Close #34 
fix/be/authorize admin-> main
- 관리자 인가 기능 정상 작동
- 앞의 PR에서 테스트 케이스가 깨지는 부분이 있어 수정...
=> [BE] 관리자 권한 버그 수정

Backend/src/main/java/com/ecobyte/ecocycle/presentation/RecyclingProductController.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/UserController.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/auth/AuthController.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/AcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/LoginAcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/RecyclingProductAcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/UserAcceptanceTest.java
Close #
chore/be/api-update -> main
- API 명세 변경에 대한 URL 변경
- 모든 백엔드 요청에는 '/api' 로 시작
=> [BE] api 명세 변경

.gitmodules, Backend/.gitignore, Backend/src/main/resources/application.yml
Close #39 
chore/be/submodule-> main
- 시크릿 키 등을 위해 서브모듈 도입
=> [BE] 서브모듈 적용

Backend/src/main/java/com/ecobyte/ecocycle/application/ReportService.java, Backend/src/main/java/com/ecobyte/ecocycle/domain/report/Report.java, Backend/src/main/java/com/ecobyte/ecocycle/domain/report/ReportRepository.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/request/RecyclingProductRequest.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/request/ReportRequest.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/ReportResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/RecyclingProductController.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/ReportController.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/UserController.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/auth/LoginAuthorization.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/auth/LoginInterceptor.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/AcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/RecyclingProductAcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/ReportAcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/UserAcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/application/UserServiceTest.java
Close #45 
feature/be/add-report -> main
- 사용자 제보하기 기능 구현
- 테스트 Fixture 분리
=> [BE] 제보하기 기능 구현

Backend/.gitignore, Backend/build.gradle, Backend/src/main/java/com/ecobyte/logging/LoggingFilter.java, Backend/src/main/java/com/ecobyte/logging/MaskingPatternLayout.java, Backend/src/main/java/com/ecobyte/logging/QueryCountInspector.java, Backend/src/main/resources/application.yml, Backend/src/main/resources/logback-spring.xml, Backend/src/main/resources/logback/console-appender.xml, Backend/src/main/resources/logback/file-error-appender.xml, Backend/src/main/resources/logback/file-info-appender.xml, Backend/src/main/resources/logback/file-slow-sql-appender.xml
Close #11 
chore/be/logging -> main
- 로깅 전략 구현
- logback 이용
=> [BE] 로깅 전략 구현

Backend/src/main/java/com/ecobyte/ecocycle/application/ReportService.java, Backend/src/main/java/com/ecobyte/ecocycle/domain/report/ReportRepository.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/ReportResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/ReportsResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/SavedReportResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/ReportController.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/ReportAcceptanceTest.java
Close #61 
feature/be/inquire-report -> main
- 관리자가 사용자들의 제보를 확인하는 기능을 구현한다.
- 기존의 ReportResponse -> SavedReportResponse 로 변경
=> [BE] 관리자 제보 확인 기능 구현

Backend/src/test/java/com/ecobyte/ecocycle/acceptance/AcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/support/DatabaseCleanUp.java
refactor/be/test-isolation -> main
- Admin 이메일을 위해 users 테이블은 격리하지 않던 부분을 개선
=> [BE] 테스트 격리 개선

Backend/src/main/java/com/ecobyte/ecocycle/application/QuizService.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/DailyQuizResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/QuizController.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/QuizAcceptanceTest.java, Backend/src/test/java/com/ecobyte/ecocycle/application/QuizServiceTest.java
refactor/be/give-daily-quiz -> main
- API 명세 변경
- Response 변경
=> [BE] Daily Quiz 내기 API 명세 변동

README.md
Close #
feature/ -> main
- 요구사항
- 변경사항
=> Add Description.md

Backend/src/main/java/com/ecobyte/ecocycle/application/RecyclingProductService.java, Backend/src/main/java/com/ecobyte/ecocycle/domain/product/ClassifiedData.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/ClassifiedProductResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/ClassifiedProductsResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/DataClassificationResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/dto/response/DataClassificationsResponse.java, Backend/src/main/java/com/ecobyte/ecocycle/presentation/RecyclingProductController.java, Backend/src/main/java/com/ecobyte/ecocycle/support/DataClassificationClient.java, Backend/src/test/java/com/ecobyte/ecocycle/acceptance/RecyclingProductAcceptanceTest.java
Close #77 
refactor/be/data-classification-api -> main
- data classification의 결과가 복수개로 변동됨에 따른 리팩토링
=> [BE] data classification 명세변동에 따른 리팩토링

Backend/src/main/java/com/ecobyte/ecocycle/support/DataClassificationClient.java
refactor/be/data-classify-api -> main
=> [BE] API 수정

Backend/src/main/java/com/ecobyte/ApplicationStartupRunner.java, Backend/src/main/java/com/ecobyte/EcoCycleApplication.java, Backend/src/main/java/com/ecobyte/ecocycle/config/HibernateConfig.java, Backend/src/main/resources/logback-spring.xml, Backend/src/test/java/com/ecobyte/logging/QueryCountInspectorTest.java
Close #48 
fix/be/logging -> main
- 적용되지 않던 필터 적용(Application의 위치 가 logging 필터보다 하위였음)
=> [BE] 로깅 필터 적용

Frontend/front/src/pages/main.jsx
Close #98 
fix/fe/main-page -> main
- 로그인 시 바로 퀴즈가 뜨게 수정
=> [FE] 로그인과 퀴즈 사이에 동기 처리

Backend/src/main/java/com/ecobyte/ecocycle/application/QuizService.java, Backend/src/main/java/com/ecobyte/ecocycle/application/ReportService.java, Backend/src/main/java/com/ecobyte/ecocycle/domain/quiz/DailyQuiz.java, Backend/src/main/java/com/ecobyte/ecocycle/support/DataClassificationClient.java
refactor/be/accept-data-server-response -> main
=> [BE] 에러 케이스 처리

Frontend/front/src/api/apis.js, Frontend/front/src/modals/menu.jsx, Frontend/front/src/pages/main.jsx, Frontend/front/src/pages/report.jsx, Frontend/front/src/styles/App.css
Close #
feature/fe/main-menu -> main
- 메인 메뉴 모달 창 구현
=> [FE] 메인 메뉴 구현

Frontend/front/src/pages/admin.jsx
Close #
refactor/fe/admin-btn -> main
- 요구사항
- 변경사항
=> [FE] 사용자 관리 버튼 삭제 

README.md
Close #
feature/ -> main
- 요구사항
- 변경사항
=> Serendipity song patch 3
